name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          # full history for correct version tag
          fetch-depth: 0

      # used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # install required libraries
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y blas-devel lapack-devel &&
            yum install -y epel-release &&
            yum install -y hdf5-devel
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD: "{cp38,cp39,cp310,cp311,cp312}-manylinux_{x86_64,aarch64}"
          # disable building PyPy wheels on all platforms
          CIBW_SKIP: pp*
          CIBW_MANYLINUX_X86_64_IMAGE:  manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
